kinesiscustomersample:
    build: .
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_ROLE_ARN:
      AWS_ROLE_SESSION_NAME: "kinesiscustomersample" # Must be greater than 2 characters.
